# Generated by Django 3.1.5 on 2021-01-14 17:45

from django.db import migrations, models
import file.validators


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[file.validators.validate_file_extension]),
        ),
    ]
